language: julia

os:
  - linux
#  - osx

julia:
  - 1.0
#   - 1.1
#  - 1.2
#  - 1.3
#  - nightly

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
#matrix:
#   allow_failures:
#   - julia: 1.3
#   - julia: nightly

env:
  - JUPYTER=$HOME/.local/bin/jupyter

notifications:
  email: false

install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py --user
  - pip3 install --user matplotlib
  - pip3 install --user jupyter

script: # the default script is equivalent to the following
  - echo $PATH
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --eval 'using Pkg; Pkg.instantiate();'
  - julia --project --eval 'using Pkg; Pkg.build();'
  - julia --project --eval 'using Pkg; Pkg.status();'
  - julia --project --eval 'using Pkg; Pkg.resolve();'
  - julia --project --eval 'using Pkg; Pkg.status();'
  - julia --project --eval 'using Pkg; Pkg.build();'
  - julia --project --eval 'using IJulia'
  - julia --project --eval 'using PyPlot'
  - $JUPYTER kernelspec list
  - $JUPYTER nbconvert --to notebook --execute --output tmp JuliaIntroduction.ipynb

