language: julia

os:
  - linux
#  - osx

julia:
   - 1.1
#  - 1.0
#  - 1.2
#  - 1.3
#  - nightly

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
#matrix:
#   allow_failures:
#   - julia: 1.3
#   - julia: nightly

notifications:
  email: false

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    packages:
    - python3-matplotlib
    - python3-nbconvert

script: # the default script is equivalent to the following
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --eval 'using Pkg; Pkg.instantiate();'
  - jupyter nbconvert --to notebook --execute --output tmp JuliaIntroduction.ipynb

